/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Nat;
export const LootId = IDL.Nat;
export const ArmorTier = IDL.Variant({
  'Light' : IDL.Null,
  'Medium' : IDL.Null,
  'Heavy' : IDL.Null,
});
export const WeaponType = IDL.Variant({
  'Shotgun' : IDL.Null,
  'Rifle' : IDL.Null,
  'Pistol' : IDL.Null,
  'Sniper' : IDL.Null,
});
export const LootType = IDL.Variant({
  'Weapon' : IDL.Null,
  'Health' : IDL.Null,
  'Armor' : IDL.Null,
});
export const LootPublic = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : LootId,
  'armorTier' : ArmorTier,
  'claimed' : IDL.Bool,
  'weaponType' : WeaponType,
  'lootType' : LootType,
  'amount' : IDL.Nat,
});
export const PlayerId = IDL.Nat;
export const KillFeedEntry = IDL.Record({
  'victimName' : IDL.Text,
  'victimId' : PlayerId,
  'killerId' : PlayerId,
  'timestamp' : IDL.Int,
  'killerName' : IDL.Text,
  'weapon' : WeaponType,
});
export const PlayerPublic = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : PlayerId,
  'alive' : IDL.Bool,
  'angle' : IDL.Float64,
  'armor' : IDL.Nat,
  'ammo' : IDL.Nat,
  'name' : IDL.Text,
  'isBot' : IDL.Bool,
  'kills' : IDL.Nat,
  'weapon' : WeaponType,
  'health' : IDL.Nat,
});
export const SafeZonePublic = IDL.Record({
  'centerX' : IDL.Float64,
  'centerY' : IDL.Float64,
  'damagePerTick' : IDL.Nat,
  'radius' : IDL.Float64,
  'nextShrinkTime' : IDL.Int,
  'phase' : IDL.Nat,
});
export const GamePhase = IDL.Variant({
  'Lobby' : IDL.Null,
  'GameOver' : IDL.Null,
  'InGame' : IDL.Null,
});
export const GameState = IDL.Record({
  'matchTime' : IDL.Int,
  'winner' : IDL.Opt(IDL.Text),
  'loots' : IDL.Vec(LootPublic),
  'killFeed' : IDL.Vec(KillFeedEntry),
  'players' : IDL.Vec(PlayerPublic),
  'safeZone' : SafeZonePublic,
  'sessionId' : SessionId,
  'phase' : GamePhase,
});
export const LeaderboardEntryPublic = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'wins' : IDL.Nat,
  'playerName' : IDL.Text,
  'kills' : IDL.Nat,
});
export const MatchResult = IDL.Record({
  'survivalTime' : IDL.Int,
  'placement' : IDL.Nat,
  'matchId' : SessionId,
  'playerName' : IDL.Text,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text], [SessionId], []),
  'getGameState' : IDL.Func(
      [SessionId],
      [IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text })],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntryPublic)], ['query']),
  'getMatchHistory' : IDL.Func([SessionId], [IDL.Vec(MatchResult)], ['query']),
  'joinSession' : IDL.Func(
      [SessionId, IDL.Text],
      [IDL.Variant({ 'ok' : PlayerId, 'err' : IDL.Text })],
      [],
    ),
  'movePlayer' : IDL.Func(
      [SessionId, PlayerId, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'pickupLoot' : IDL.Func(
      [SessionId, PlayerId, LootId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'shootBullet' : IDL.Func(
      [SessionId, PlayerId, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'startGame' : IDL.Func(
      [SessionId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'tickGame' : IDL.Func(
      [SessionId],
      [IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text })],
      [],
    ),
  'useHealthItem' : IDL.Func(
      [SessionId, PlayerId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Nat;
  const LootId = IDL.Nat;
  const ArmorTier = IDL.Variant({
    'Light' : IDL.Null,
    'Medium' : IDL.Null,
    'Heavy' : IDL.Null,
  });
  const WeaponType = IDL.Variant({
    'Shotgun' : IDL.Null,
    'Rifle' : IDL.Null,
    'Pistol' : IDL.Null,
    'Sniper' : IDL.Null,
  });
  const LootType = IDL.Variant({
    'Weapon' : IDL.Null,
    'Health' : IDL.Null,
    'Armor' : IDL.Null,
  });
  const LootPublic = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : LootId,
    'armorTier' : ArmorTier,
    'claimed' : IDL.Bool,
    'weaponType' : WeaponType,
    'lootType' : LootType,
    'amount' : IDL.Nat,
  });
  const PlayerId = IDL.Nat;
  const KillFeedEntry = IDL.Record({
    'victimName' : IDL.Text,
    'victimId' : PlayerId,
    'killerId' : PlayerId,
    'timestamp' : IDL.Int,
    'killerName' : IDL.Text,
    'weapon' : WeaponType,
  });
  const PlayerPublic = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : PlayerId,
    'alive' : IDL.Bool,
    'angle' : IDL.Float64,
    'armor' : IDL.Nat,
    'ammo' : IDL.Nat,
    'name' : IDL.Text,
    'isBot' : IDL.Bool,
    'kills' : IDL.Nat,
    'weapon' : WeaponType,
    'health' : IDL.Nat,
  });
  const SafeZonePublic = IDL.Record({
    'centerX' : IDL.Float64,
    'centerY' : IDL.Float64,
    'damagePerTick' : IDL.Nat,
    'radius' : IDL.Float64,
    'nextShrinkTime' : IDL.Int,
    'phase' : IDL.Nat,
  });
  const GamePhase = IDL.Variant({
    'Lobby' : IDL.Null,
    'GameOver' : IDL.Null,
    'InGame' : IDL.Null,
  });
  const GameState = IDL.Record({
    'matchTime' : IDL.Int,
    'winner' : IDL.Opt(IDL.Text),
    'loots' : IDL.Vec(LootPublic),
    'killFeed' : IDL.Vec(KillFeedEntry),
    'players' : IDL.Vec(PlayerPublic),
    'safeZone' : SafeZonePublic,
    'sessionId' : SessionId,
    'phase' : GamePhase,
  });
  const LeaderboardEntryPublic = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'wins' : IDL.Nat,
    'playerName' : IDL.Text,
    'kills' : IDL.Nat,
  });
  const MatchResult = IDL.Record({
    'survivalTime' : IDL.Int,
    'placement' : IDL.Nat,
    'matchId' : SessionId,
    'playerName' : IDL.Text,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text], [SessionId], []),
    'getGameState' : IDL.Func(
        [SessionId],
        [IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text })],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntryPublic)],
        ['query'],
      ),
    'getMatchHistory' : IDL.Func(
        [SessionId],
        [IDL.Vec(MatchResult)],
        ['query'],
      ),
    'joinSession' : IDL.Func(
        [SessionId, IDL.Text],
        [IDL.Variant({ 'ok' : PlayerId, 'err' : IDL.Text })],
        [],
      ),
    'movePlayer' : IDL.Func(
        [SessionId, PlayerId, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'pickupLoot' : IDL.Func(
        [SessionId, PlayerId, LootId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'shootBullet' : IDL.Func(
        [SessionId, PlayerId, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'startGame' : IDL.Func(
        [SessionId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'tickGame' : IDL.Func(
        [SessionId],
        [IDL.Variant({ 'ok' : GameState, 'err' : IDL.Text })],
        [],
      ),
    'useHealthItem' : IDL.Func(
        [SessionId, PlayerId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };