/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArmorTier = { 'Light' : null } |
  { 'Medium' : null } |
  { 'Heavy' : null };
export type GamePhase = { 'Lobby' : null } |
  { 'GameOver' : null } |
  { 'InGame' : null };
export interface GameState {
  'matchTime' : bigint,
  'winner' : [] | [string],
  'loots' : Array<LootPublic>,
  'killFeed' : Array<KillFeedEntry>,
  'players' : Array<PlayerPublic>,
  'safeZone' : SafeZonePublic,
  'sessionId' : SessionId,
  'phase' : GamePhase,
}
export interface KillFeedEntry {
  'victimName' : string,
  'victimId' : PlayerId,
  'killerId' : PlayerId,
  'timestamp' : bigint,
  'killerName' : string,
  'weapon' : WeaponType,
}
export interface LeaderboardEntryPublic {
  'gamesPlayed' : bigint,
  'wins' : bigint,
  'playerName' : string,
  'kills' : bigint,
}
export type LootId = bigint;
export interface LootPublic {
  'x' : number,
  'y' : number,
  'id' : LootId,
  'armorTier' : ArmorTier,
  'claimed' : boolean,
  'weaponType' : WeaponType,
  'lootType' : LootType,
  'amount' : bigint,
}
export type LootType = { 'Weapon' : null } |
  { 'Health' : null } |
  { 'Armor' : null };
export interface MatchResult {
  'survivalTime' : bigint,
  'placement' : bigint,
  'matchId' : SessionId,
  'playerName' : string,
  'kills' : bigint,
}
export type PlayerId = bigint;
export interface PlayerPublic {
  'x' : number,
  'y' : number,
  'id' : PlayerId,
  'alive' : boolean,
  'angle' : number,
  'armor' : bigint,
  'ammo' : bigint,
  'name' : string,
  'isBot' : boolean,
  'kills' : bigint,
  'weapon' : WeaponType,
  'health' : bigint,
}
export interface SafeZonePublic {
  'centerX' : number,
  'centerY' : number,
  'damagePerTick' : bigint,
  'radius' : number,
  'nextShrinkTime' : bigint,
  'phase' : bigint,
}
export type SessionId = bigint;
export type WeaponType = { 'Shotgun' : null } |
  { 'Rifle' : null } |
  { 'Pistol' : null } |
  { 'Sniper' : null };
export interface _SERVICE {
  'createSession' : ActorMethod<[string], SessionId>,
  'getGameState' : ActorMethod<
    [SessionId],
    { 'ok' : GameState } |
      { 'err' : string }
  >,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntryPublic>>,
  'getMatchHistory' : ActorMethod<[SessionId], Array<MatchResult>>,
  'joinSession' : ActorMethod<
    [SessionId, string],
    { 'ok' : PlayerId } |
      { 'err' : string }
  >,
  'movePlayer' : ActorMethod<
    [SessionId, PlayerId, number, number, number],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'pickupLoot' : ActorMethod<
    [SessionId, PlayerId, LootId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'shootBullet' : ActorMethod<
    [SessionId, PlayerId, number, number],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'startGame' : ActorMethod<
    [SessionId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'tickGame' : ActorMethod<
    [SessionId],
    { 'ok' : GameState } |
      { 'err' : string }
  >,
  'useHealthItem' : ActorMethod<
    [SessionId, PlayerId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];