/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SafeZonePublic {
    centerX: number;
    centerY: number;
    damagePerTick: bigint;
    radius: number;
    nextShrinkTime: bigint;
    phase: bigint;
}
export interface LootPublic {
    x: number;
    y: number;
    id: LootId;
    armorTier: ArmorTier;
    claimed: boolean;
    weaponType: WeaponType;
    lootType: LootType;
    amount: bigint;
}
export type SessionId = bigint;
export type LootId = bigint;
export interface GameState {
    matchTime: bigint;
    winner?: string;
    loots: Array<LootPublic>;
    killFeed: Array<KillFeedEntry>;
    players: Array<PlayerPublic>;
    safeZone: SafeZonePublic;
    sessionId: SessionId;
    phase: GamePhase;
}
export type PlayerId = bigint;
export interface MatchResult {
    survivalTime: bigint;
    placement: bigint;
    matchId: SessionId;
    playerName: string;
    kills: bigint;
}
export interface LeaderboardEntryPublic {
    gamesPlayed: bigint;
    wins: bigint;
    playerName: string;
    kills: bigint;
}
export interface KillFeedEntry {
    victimName: string;
    victimId: PlayerId;
    killerId: PlayerId;
    timestamp: bigint;
    killerName: string;
    weapon: WeaponType;
}
export interface PlayerPublic {
    x: number;
    y: number;
    id: PlayerId;
    alive: boolean;
    angle: number;
    armor: bigint;
    ammo: bigint;
    name: string;
    isBot: boolean;
    kills: bigint;
    weapon: WeaponType;
    health: bigint;
}
export enum ArmorTier {
    Light = "Light",
    Medium = "Medium",
    Heavy = "Heavy"
}
export enum GamePhase {
    Lobby = "Lobby",
    GameOver = "GameOver",
    InGame = "InGame"
}
export enum LootType {
    Weapon = "Weapon",
    Health = "Health",
    Armor = "Armor"
}
export enum WeaponType {
    Shotgun = "Shotgun",
    Rifle = "Rifle",
    Pistol = "Pistol",
    Sniper = "Sniper"
}
export interface backendInterface {
    createSession(playerName: string): Promise<SessionId>;
    getGameState(sessionId: SessionId): Promise<{
        __kind__: "ok";
        ok: GameState;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeaderboard(): Promise<Array<LeaderboardEntryPublic>>;
    getMatchHistory(sessionId: SessionId): Promise<Array<MatchResult>>;
    joinSession(sessionId: SessionId, playerName: string): Promise<{
        __kind__: "ok";
        ok: PlayerId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    movePlayer(sessionId: SessionId, playerId: PlayerId, x: number, y: number, angle: number): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    pickupLoot(sessionId: SessionId, playerId: PlayerId, lootId: LootId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    shootBullet(sessionId: SessionId, playerId: PlayerId, targetX: number, targetY: number): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    startGame(sessionId: SessionId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    tickGame(sessionId: SessionId): Promise<{
        __kind__: "ok";
        ok: GameState;
    } | {
        __kind__: "err";
        err: string;
    }>;
    useHealthItem(sessionId: SessionId, playerId: PlayerId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { ArmorTier as _ArmorTier, GamePhase as _GamePhase, GameState as _GameState, KillFeedEntry as _KillFeedEntry, LootId as _LootId, LootPublic as _LootPublic, LootType as _LootType, PlayerId as _PlayerId, PlayerPublic as _PlayerPublic, SafeZonePublic as _SafeZonePublic, SessionId as _SessionId, WeaponType as _WeaponType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSession(arg0: string): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async getGameState(arg0: SessionId): Promise<{
        __kind__: "ok";
        ok: GameState;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMatchHistory(arg0: SessionId): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchHistory(arg0);
            return result;
        }
    }
    async joinSession(arg0: SessionId, arg1: string): Promise<{
        __kind__: "ok";
        ok: PlayerId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0, arg1);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0, arg1);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async movePlayer(arg0: SessionId, arg1: PlayerId, arg2: number, arg3: number, arg4: number): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.movePlayer(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.movePlayer(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async pickupLoot(arg0: SessionId, arg1: PlayerId, arg2: LootId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.pickupLoot(arg0, arg1, arg2);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pickupLoot(arg0, arg1, arg2);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async shootBullet(arg0: SessionId, arg1: PlayerId, arg2: number, arg3: number): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.shootBullet(arg0, arg1, arg2, arg3);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shootBullet(arg0, arg1, arg2, arg3);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async startGame(arg0: SessionId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async tickGame(arg0: SessionId): Promise<{
        __kind__: "ok";
        ok: GameState;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.tickGame(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tickGame(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async useHealthItem(arg0: SessionId, arg1: PlayerId): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.useHealthItem(arg0, arg1);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useHealthItem(arg0, arg1);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ArmorTier_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArmorTier): ArmorTier {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GamePhase_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_KillFeedEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KillFeedEntry): KillFeedEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LootPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LootPublic): LootPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LootType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LootType): LootType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerPublic): PlayerPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WeaponType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeaponType): WeaponType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    victimName: string;
    victimId: _PlayerId;
    killerId: _PlayerId;
    timestamp: bigint;
    killerName: string;
    weapon: _WeaponType;
}): {
    victimName: string;
    victimId: PlayerId;
    killerId: PlayerId;
    timestamp: bigint;
    killerName: string;
    weapon: WeaponType;
} {
    return {
        victimName: value.victimName,
        victimId: value.victimId,
        killerId: value.killerId,
        timestamp: value.timestamp,
        killerName: value.killerName,
        weapon: from_candid_WeaponType_n10(_uploadFile, _downloadFile, value.weapon)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: number;
    y: number;
    id: _PlayerId;
    alive: boolean;
    angle: number;
    armor: bigint;
    ammo: bigint;
    name: string;
    isBot: boolean;
    kills: bigint;
    weapon: _WeaponType;
    health: bigint;
}): {
    x: number;
    y: number;
    id: PlayerId;
    alive: boolean;
    angle: number;
    armor: bigint;
    ammo: bigint;
    name: string;
    isBot: boolean;
    kills: bigint;
    weapon: WeaponType;
    health: bigint;
} {
    return {
        x: value.x,
        y: value.y,
        id: value.id,
        alive: value.alive,
        angle: value.angle,
        armor: value.armor,
        ammo: value.ammo,
        name: value.name,
        isBot: value.isBot,
        kills: value.kills,
        weapon: from_candid_WeaponType_n10(_uploadFile, _downloadFile, value.weapon),
        health: value.health
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchTime: bigint;
    winner: [] | [string];
    loots: Array<_LootPublic>;
    killFeed: Array<_KillFeedEntry>;
    players: Array<_PlayerPublic>;
    safeZone: _SafeZonePublic;
    sessionId: _SessionId;
    phase: _GamePhase;
}): {
    matchTime: bigint;
    winner?: string;
    loots: Array<LootPublic>;
    killFeed: Array<KillFeedEntry>;
    players: Array<PlayerPublic>;
    safeZone: SafeZonePublic;
    sessionId: SessionId;
    phase: GamePhase;
} {
    return {
        matchTime: value.matchTime,
        winner: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.winner)),
        loots: from_candid_vec_n5(_uploadFile, _downloadFile, value.loots),
        killFeed: from_candid_vec_n14(_uploadFile, _downloadFile, value.killFeed),
        players: from_candid_vec_n17(_uploadFile, _downloadFile, value.players),
        safeZone: value.safeZone,
        sessionId: value.sessionId,
        phase: from_candid_GamePhase_n20(_uploadFile, _downloadFile, value.phase)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: number;
    y: number;
    id: _LootId;
    armorTier: _ArmorTier;
    claimed: boolean;
    weaponType: _WeaponType;
    lootType: _LootType;
    amount: bigint;
}): {
    x: number;
    y: number;
    id: LootId;
    armorTier: ArmorTier;
    claimed: boolean;
    weaponType: WeaponType;
    lootType: LootType;
    amount: bigint;
} {
    return {
        x: value.x,
        y: value.y,
        id: value.id,
        armorTier: from_candid_ArmorTier_n8(_uploadFile, _downloadFile, value.armorTier),
        claimed: value.claimed,
        weaponType: from_candid_WeaponType_n10(_uploadFile, _downloadFile, value.weaponType),
        lootType: from_candid_LootType_n12(_uploadFile, _downloadFile, value.lootType),
        amount: value.amount
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameState;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GameState;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameState_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Shotgun: null;
} | {
    Rifle: null;
} | {
    Pistol: null;
} | {
    Sniper: null;
}): WeaponType {
    return "Shotgun" in value ? WeaponType.Shotgun : "Rifle" in value ? WeaponType.Rifle : "Pistol" in value ? WeaponType.Pistol : "Sniper" in value ? WeaponType.Sniper : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Weapon: null;
} | {
    Health: null;
} | {
    Armor: null;
}): LootType {
    return "Weapon" in value ? LootType.Weapon : "Health" in value ? LootType.Health : "Armor" in value ? LootType.Armor : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lobby: null;
} | {
    GameOver: null;
} | {
    InGame: null;
}): GamePhase {
    return "Lobby" in value ? GamePhase.Lobby : "GameOver" in value ? GamePhase.GameOver : "InGame" in value ? GamePhase.InGame : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PlayerId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PlayerId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Light: null;
} | {
    Medium: null;
} | {
    Heavy: null;
}): ArmorTier {
    return "Light" in value ? ArmorTier.Light : "Medium" in value ? ArmorTier.Medium : "Heavy" in value ? ArmorTier.Heavy : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KillFeedEntry>): Array<KillFeedEntry> {
    return value.map((x)=>from_candid_KillFeedEntry_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerPublic>): Array<PlayerPublic> {
    return value.map((x)=>from_candid_PlayerPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LootPublic>): Array<LootPublic> {
    return value.map((x)=>from_candid_LootPublic_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
